# Use the official Python slim image as the base
FROM python:3.13.2-slim-bookworm

# Prevent Python from writing .pyc files and enable unbuffered logging
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set the working directory in the container
WORKDIR /app

# Copy requirements file to the working directory
COPY requirements.txt /app/

# Upgrade pip and install Python dependencies
RUN pip install --upgrade pip && pip install -r requirements.txt

# Copy the entire project to the working directory
COPY . /app/

# Expose port 8000 for the Django app
EXPOSE 8000

# Command to run the Django application using gunicorn.
# Replace 'myproject' with your Django project directory name.
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
